# Dependencies
markdown:         kramdown  
highlighter:      rouge

# Setup
title:            António Santos
tagline:          'A Jekyll theme'
description:      'Portfolio & Blog'
url:              http://tonysantos9.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5
paginate_path: "blog/page:num/"

# Custom vars
version:          2.1.0

plugins:
  - jekyll-paginate
  - jekyll-gist

github:
  repo:           https://github.com/poole/hyde
